### ISSUE TITLE
请问MacOS 13.3.1 M1 Max  是不是不支持？好像是找不到GPU

### ISSUE THREAD

**Issue by Restry** [X-PLUG/ChatPLUG#1]
请问MacOS 13.3.1 M1 Max  是不是不支持？好像是找不到GPU

2023-04-20 14:48:06,856 - modelscope - INFO - PyTorch version 2.1.0.dev20230414 Found.
2023-04-20 14:48:06,856 - modelscope - INFO - Loading ast index from /Users/lewaylee/.cache/modelscope/ast_indexer
2023-04-20 14:48:06,888 - modelscope - INFO - No valid ast index found from /Users/lewaylee/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2023-04-20 14:48:06,926 - modelscope - INFO - Loading done! Current index file version is 1.5.0, with md5 77c50e7053fa0988be9fa0099573ada5 and a total number of 860 components indexed
2023-04-20 14:48:07,940 - modelscope - INFO - Use user-specified model revision: v1.0.1
2023-04-20 14:48:08,277 - modelscope - INFO - initiate model from /Users/lewaylee/.cache/modelscope/hub/damo/ChatPLUG-240M
2023-04-20 14:48:08,277 - modelscope - INFO - initiate model from location /Users/lewaylee/.cache/modelscope/hub/damo/ChatPLUG-240M.
2023-04-20 14:48:08,278 - modelscope - INFO - initialize model from /Users/lewaylee/.cache/modelscope/hub/damo/ChatPLUG-240M
| _IncompatibleKeys(missing_keys=[], unexpected_keys=['backbone.loss.generator.dense.weight', 'backbone.loss.generator.dense.bias', 'backbone.loss.criterion.one_hot'])
2023-04-20 14:48:14,821 - modelscope - INFO - cuda is not available, using cpu instead.
Traceback (most recent call last):
  File "/Users/lewaylee/Projects/hub_runtime/ChatPLUG-240M.py", line 47, in <module>
    result = pipeline_ins(input,**kwargs)
  File "/Users/lewaylee/miniconda3/envs/pytorch-gpu/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 212, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/Users/lewaylee/miniconda3/envs/pytorch-gpu/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 251, in _process_single
    out = self.postprocess(out, **postprocess_params)
  File "/Users/lewaylee/miniconda3/envs/pytorch-gpu/lib/python3.10/site-packages/modelscope/pipelines/nlp/fid_dialogue_pipeline.py", line 198, in postprocess
    hypotheses[0], skip_special_tokens=self.is_t5)
UnboundLocalError: local variable 'hypotheses' referenced before assignment

**Comment by chenhehong** [comment]
你好，这个是代码支持cpu推理的bug，mass下一个sdk版本会修复该问题。
当前版本临时的解决方法是将 modelscope/pipelines/nlp/fid_dialogue_pipeline.py 文件194-195行中`if torch.cuda.is_available():
hypotheses = inputs.sequences.detach().cpu().tolist()`修改为`hypotheses = inputs.sequences.detach().cpu().tolist()`

**Comment by Restry** [comment]
```

# 支持输入多段外部知识文本，进行知识增强
know_list = [
    "《狂飙》由徐纪周执导的。《狂飙》的导演徐纪周也是编剧之一，代表作品有《永不磨灭的番号》《特战荣耀》《心理罪之城市之光》《杀虎口》《胭脂》等",
    "《狂飙》（The Knockout）是一部由 张译、张颂文、李一桐、张志坚 领衔主演，韩童生 特邀主演，吴健、郝平 友情出演，高叶、贾冰、李健 主演，徐纪周 执导，朱俊懿、徐纪周 担任总编剧的 刑侦",
    "狂飙是由中央政法委宣传教育局，中央政法委政法信息中心指导，爱奇艺，留白影视出品，徐纪周执导，张译，李一桐，张志坚领衔主演的刑侦剧。不是。是徐纪周，1976年12月19日出生，毕业于中央戏剧"
]

input = {
    "history": "你好[SEP]你好!很高兴与你交流![SEP]狂飙的导演是谁呀",
    "bot_profile": "我是达摩院的语言模型ChatPLUG， 是基于海量数据训练得到。",
    # 推理时，会根据[SEP]符号拆分为多段文本，分别和context合并后输入模型中，以节省计算量
    "knowledge": "[SEP]".join(know_list),
}
```
谢谢 @chenhehong 的回复，我还有几个剖一，不知道是不是可以帮忙回答，谢谢：

- 官方示例中的 know_list 的知识增强最大支持多少内容？ 我试过2w个字 64G的内存受不了了 
- 我如果想对本地知识库进行问答可以基于know_list做吗？
- 我看到官方readme里面好像还能支持搜索引擎插件， 这个是如何实现的？

**Comment by chenhehong** [comment]
- 知识增强最大支持的token数和机器显存大小有关，我们的推理测试一般只用千级别的token数，2w个字64G应该吃不消
- 本地知识库进行问答可以基于know_list>>可以
- chatplug是调用夸克api接口实现的，该api接口是付费接口，暂时提供不了

**Comment by Restry** [comment]
@chenhehong 谢谢，请问https://www.modelscope.cn/studios/damo/role_play_chat/files 这里面的roles_json和源码 有公开吗？想自己跑起来试一下
```
app_config.py 

import os
import json
import requests
class AppConfig(object):
    ALREADY_CONVERTED_MARK = "<!-- ALREADY CONVERTED BY PARSER. -->"

    with open(os.path.join(os.path.dirname(__file__), 'main.css'), "r", encoding="utf-8") as f:
        MAIN_CSS_CODE = f.read()
    
    roles_json = os.getenv('roles_json')
    print('roles json', roles_json)
    ROLES = json.loads(requests.get(roles_json).content.decode('utf-8'))
```
